version: "2"

services: 

  # PROM --------------------------------

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #     - "./alert.rules:/etc/prometheus/alert.rules"
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - "monitoring-network"
  
  # prometheus:
  #   image: prom/prometheus
  #   # user: root
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - prometheus_data:/prometheus
  #   command:
  #     # - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/etc/prometheus'
  #     # - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     # - '--web.console.templates=/etc/prometheus/consoles'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #     - '--storage.tsdb.retention.time=200h'
  #     - '--web.enable-lifecycle'
  #   restart: unless-stopped
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - "monitoring-network"
  #   # labels:
  #   #   org.label-schema.group: "monitoring"

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   # volumes:
  #   #   - "grafana:/var/lib/grafana"
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - "monitoring-network"
  #   depends_on:
  #     - prometheus

  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   # volumes:
  #   #   - "alertmanager:/etc/alertmanager"
  #   ports:
  #     - 9093:9093
  #   networks:
  #     - "monitoring-network"


# apm:
#     image: docker.elastic.co/apm/apm-server:7.6.1
#     ports:
#       - 8200:8200
#     volumes:
#       - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml"
#     environment:
#       output.elasticsearch.hosts: '["elasticsearch:9200"]'

networks: 
  apm:
    driver: bridge
  # monitoring-network:
  #   driver: bridge

# volumes:
  # elastic-graylog:
  #   driver: local
  # mongodb:
  #   driver: local
  # kibana:
  #   driver: local
  # graylog:
  #   driver: local
  # elastic-elk:
  #   driver: local
  # logstash:
  #   driver: local
  # grafana:
  #   driver: local
  # alertmanager:
  #   driver: local
  # prometheus_data: {}
  # grafana_data: {}
