version: "2"

services: 

  # GRAYLOG --------------------------------

  elastic-graylog:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
    ports:
      - "9210:9200"
      # - "9310:9300"
    container_name: elastic-graylog
    restart: always
    environment: 
      - node.name=elastic-graylog
      - "TZ=America/Sao_Paulo"
      - cluster.name=graylog
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      # Disable X-Pack security
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.audit.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      # - "ES_JAVA_OPTS=-Xms1g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    networks: 
      - apm
    volumes:
      - "elastic-graylog-data:/usr/share/elasticsearch/data"
      # - "./config/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    #   - "./config/elastic/data-graylog:/usr/share/elasticsearch/data"
    #   - "./config/elastic/plugins:/usr/share/elasticsearch/plugins"
    tty: true

  mongodb:
    container_name: mongodb
    image: mongo:4
    restart: always
    ports:
        - "27017:27017"
    environment:
      - "TZ=America/Sao_Paulo"
    networks:
      - apm
    volumes:
      - "mongodb-data:/var/data"
      # - "./config/mongodb/data-graylog:/var/data"
    tty: true

  graylog:
    image: graylog/graylog:3.2.2
    container_name: graylog
    restart: always
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      TZ: America/Sao_Paulo
      GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: 2gb
      GRAYLOG_ROOT_TIMEZONE: America/Sao_Paulo
      # GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      # GRAYLOG_ELASTICSEARCH_HOSTS: "http://127.0.0.1:9210"
      # GRAYLOG_TRANSPORT_EMAIL_ENABLED: 'true'
      # GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: mail.example.com
      # GRAYLOG_TRANSPORT_EMAIL_PORT: '587'
      # GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: 'true'
      # GRAYLOG_TRANSPORT_EMAIL_USE_TLS: 'true'
      # GRAYLOG_TRANSPORT_EMAIL_USE_SSL: 'false'
      # GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME: admin@example.com
      # GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD: xxxxxx
      # GRAYLOG_TRANSPORT_EMAIL_SUBJECT_PREFIX: '[graylog]'
      # GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL: graylog@example.com
      # GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL: https://graylog.example.com
    stdin_open: true
    links:
      - mongodb:mongo
      - elastic-graylog:elasticsearch
    depends_on:
      - mongodb
      - elastic-graylog
    networks:
      - apm
    ports:
      - "9000:9000"
      - "12202:12202/udp"
    volumes:
      - "graylog-data:/usr/share/graylog/data"
      - ./graylog-plugin/graylog-plugin-backup-configuration-1.0.2.jar:/usr/share/graylog/data/plugin/graylog-plugin-backup-configuration-1.0.2.jar
      - ./graylog-plugin/graylog-plugin-beats-2.5.1.jar:/usr/share/graylog/data/plugin/graylog-plugin-beats-2.5.1.jar
      - ./graylog-plugin/graylog-plugin-slack-3.1.0.jar:/usr/share/graylog/data/plugin/graylog-plugin-slack-3.1.0.jar
    tty: true

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash
    ports:
      - "12201:12201/udp"
      - "5000:5000"
    links:
      - graylog:graylog
      # - elastic-graylog:elasticsearch
    restart: always
    environment: 
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    # depends_on:
    #   - elastic-graylog
    volumes:
      - "logstash-data:/usr/share/logstash/config" 
      # - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./logs:/tmp/logs
    # command: "sh -c 'bin/logstash-plugin install logstash-output-gelf && bin/logstash-plugin install logstash-filter-translate && bin/logstash-plugin install logstash-filter-json && logstash -f /etc/logstash/conf.d/logstash.conf'"
    command: "sh -c 'bin/logstash-plugin install logstash-output-gelf && logstash -f /usr/share/logstash/config/logstash.conf'"
    networks:
      - apm

  http-graylog:
    container_name: http-graylog
    image: httpd:latest
    restart: always
    environment:                                                    
      - "TZ=America/Sao_Paulo"
    ports:
      - "82:80"
    tty: true
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12202"
        tag: "http-graylog-12202"
    networks:
      - apm

  http-logstash:
    container_name: http-logstash
    image: httpd:latest
    restart: always
    environment:                                                    
      - "TZ=America/Sao_Paulo"
    ports:
      - "81:80"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "http-logstash-12201"
    networks:
      - apm

networks: 
  apm:
    driver: bridge

volumes:
  elastic-graylog-data:
    driver: local
  mongodb-data:
    driver: local
  graylog-data:
    driver: local
  logstash-data:
    driver: local
